app/todo/models.py
from app import db


class Todo(db.Model):

  __tablename__ = 'todos'

  id = db.Column(db.Integer, primary_key=True)
  body = db.Column(db.Text)
  priority = db.Column(db.String(50), default=None)
  tags = db.Column(db.String(50), default=None)
  done = db.Column(db.Boolean, default=False)
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)


class Tag(db.Model):
  __talblename__ = 'tags'

  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(50))

app/todo/forms.py
from flask_wtf import Form
from wtforms import TextField, SelectField, StringField
from .models import Tag

tag_choices = Tag.query.all()

class TodoForm(Form):
  body = TextField('add todo')
  priority = SelectField('Priority', choices=['High', 'Medium', 'Low'])
  tags = SelectField('Tags', choices=tag_choices)

class TagForm(Form):
  name = StringField('Tag name')

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)
migrate = Migrate(app, db)
login_manager = LoginManager()
login_manager.init_app(app)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    

from .todo.models import Todo
from .auth.models import User

@app.errorhandler(404)
def not_found(error):
  return render_template('404.html'), 404


from app.auth.views import bp as authModule
from app.todo.views import bp as todoModule
app.register_blueprint(authModule)
app.register_blueprint(todoModule)



# Later on you'll import the other blueprints the same way:
#from app.comments.views import mod as commentsModule
#from app.posts.views import mod as postsModule
#app.register_blueprint(commentsModule)
#app.register_blueprint(postsModule)

app/todo/views/__init__.py
from flask import Blueprint

bp = Blueprint('todo', __name__, url_prefix='/')

from . import calendar, team, projects, dashboard

app/todo/views/calendar.py
from flask_login import login_required
from flask import render_template

from . import bp




@bp.route('/calendar')
@login_required
def calendar():
  calendar = True
  context = {
    'calendar': calendar,
  }
  return render_template('todo/calendar.html', context=context)

app/todo/views/dashboard.py
from app.todo.forms import TodoForm
from flask import request, render_template, redirect, url_for
from flask_login import login_required, current_user

from . import bp
from app.todo.models import Todo
from app import db
from app.todo.decorators import get_todo



@bp.route('')
@login_required
def index():

  todos = Todo.query.all()

  dashboard = True

  context = {
    'dashboard': dashboard,
    'todos': todos,
  }

  return render_template('todo/index.html', context=context, form=TodoForm())

@bp.route('/done')
@login_required
def show_finished():

  todos = Todo.query.filter_by(done=True).all()

  dashboard = True

  context = {
    'dashboard': dashboard,
    'todos': todos,
  }

  return render_template('todo/index.html', context=context, form=TodoForm())

@bp.route('/todo')
@login_required
def show_undone():

  todos = Todo.query.filter_by(done=False).all()

  dashboard = True

  context = {
    'dashboard': dashboard,
    'todos': todos,
  }

  return render_template('todo/index.html', context=context, form=TodoForm())




@bp.route('/create', methods=['POST'])
@login_required
def create():
  form = TodoForm(request.form)

  if request.method == 'POST':
    todo = Todo(
      body=form.body.data,
      priority=form.priority.data,
      tags=form.tags.data,
      user_id=current_user.id
    )

    db.session.add(todo)
    db.session.commit()
  
  return redirect(url_for('todo.index'))



@bp.route('/update/<int:id>', methods=('GET', 'POST'))
@login_required
def update(id):
    
  todos = Todo.query.all()

  dashboard = True
  edit = True

  context = {
    'dashboard': dashboard,
    'todos': todos,
    'edit': edit,
  }
  edit_todo = get_todo(id)

  edit_form = TodoForm()
  if request.method == 'POST':
  
    edit_todo.body=edit_form.body.data
    edit_todo.priority=edit_form.priority.data
    edit_todo.tags=edit_form.tags.data
    edit_todo.user_id=current_user.id
    
    
    db.session.commit()
    return redirect(url_for('todo.index'))
  return render_template('todo/index.html', edit_todo=edit_todo, context=context, edit_form=TodoForm(obj=edit_todo), form=TodoForm())



@bp.route('/check_off/<int:id>')
@login_required
def check_off(id):

  todo = get_todo(id)
    
  todo.done = True
  db.session.commit()
  return redirect(url_for('todo.index'))

app/todo/views/projects.py
from flask_login import login_required
from flask import render_template

from . import bp



@bp.route('/projects')
@login_required
def projects():
  projects = True
  context = {
    'projects': projects,
  }
  return render_template('todo/projects.html', context=context)

app/todo/views/team.py
from flask_login import login_required
from flask import render_template

from . import bp


@bp.route('/team')
@login_required
def team():
  team = True
  context = {
    'team': team,
  }
  return render_template('todo/team.html', context=context)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> {% block title %}{% endblock title %} - TodoP</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='tailwind.css') }}">
  <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
</head>
<body>
  

  {% block navbar %}{% endblock navbar %}
  
  {% block errors %}{% endblock errors %}

  {% block menu %}{% endblock menu %}

  {% block content %}{% endblock content %}


</body>
</html>

app/templates/components/flashed_messages.html
{% block errors %}
  

{% for message in get_flashed_messages() %}
  

  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="rounded-md bg-yellow-50 p-4 text-center">
    <div class="flex justify-center">
      <div class="flex-shrink-0">
        <!-- Heroicon name: exclamation -->
        <svg class="h-5 w-5 text-yellow-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <h3 class="text-sm font-medium text-yellow-800">
          {{ message }}
        </h3>
        <!-- <div class="mt-2 text-sm text-yellow-700">
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid pariatur, ipsum similique veniam quo totam eius aperiam dolorum.
          </p>
        </div> -->
      </div>
    </div>
  </div>



{% endfor %}





{% endblock errors %}

app/templates/components/menu.html
{% block menu %}
  

  <div class="my-4 py-2 bg-fuchsia-200 rounded-md mx-auto max-w-7xl flex flex-row justify-end">
    
    <!-- This example requires Tailwind CSS v2.0+ -->
    <div x-data="{ openMenu: false }" class="relative inline-block text-left">
      <div>
        <button @click="openMenu = !openMenu" type="button" class="flex flex-row bg-fuchsia-100 text-fuchsia-900 px-2 rounded-md mr-4 text-sm font-light hover:scale-150 hover:bg-fuchsia-300 hover:text-white hover:font-normal focus:outline-none focus:ring-1 ring-fuchsia-400" id="options-menu" aria-haspopup="true" aria-expanded="true">
          Show
          <!-- Heroicon name: chevron-down -->
          <svg class="-mr-1 ml-2 h-5 w-5 text-fuchsia-900" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
          </svg>
        </button>
      </div>

      <!--
        Dropdown panel, show/hide based on dropdown state.

        Entering: "transition ease-out duration-100"
          From: "transform opacity-0 scale-95"
          To: "transform opacity-100 scale-100"
        Leaving: "transition ease-in duration-75"
          From: "transform opacity-100 scale-100"
          To: "transform opacity-0 scale-95"
      -->
      <div x-show="openMenu" class="origin-top-right absolute right-0 mt-2 w-20 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5">
        <div class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
          <a href="{{ url_for('todo.show_undone') }}" class="block px-4 py-1 text-sm text-fuchsia-700 hover:bg-fuchsia-100 hover:text-fuchsia-900 text-center" role="menuitem">To do</a>
          <a href="{{ url_for('todo.show_finished') }}" class="block px-4 py-1 text-sm text-fuchsia-700 hover:bg-fuchsia-100 hover:text-fuchsia-900 text-center" role="menuitem">Done</a>
          <a href="{{ url_for('todo.index') }}" class="block px-4 py-1 text-sm text-fuchsia-700 hover:bg-fuchsia-100 hover:text-fuchsia-900 text-center" role="menuitem">All</a>
          <!-- <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900" role="menuitem">License</a>
          <form method="POST" action="#">
            <button type="submit" class="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900" role="menuitem">
              Sign out
            </button>
          </form> -->
        </div>
      </div>
    </div>
  </div>


{% endblock menu %}

app/templates/forms/macros.html
{% macro render_field(field) %}
    <div class="form_field">
    {{ field.label(class="label") }}
    {% if field.errors %}
        {% set css_class = 'has_error ' + kwargs.pop('class', '') %}
        {{ field(class=css_class, **kwargs) }}
        <ul class="errors">{% for error in field.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
    {% else %}
        {{ field(**kwargs) }}
    {% endif %}
    </div>
{% endmacro %}

app/templates/todo/calendar.html
{% extends 'base.html' %}


{% block title %}
  Calendar
{% endblock title %}



{% block errors %}
  {% include 'components/flashed_messages.html' %}
{% endblock errors %}



{% block navbar %}
  {% include 'components/navbar.html' %}
{% endblock navbar %}




{% block content %}
calendar
{% endblock content %}

app/templates/todo/index.html
{% extends 'base.html' %}


{% block title %}
  Dashboard
{% endblock title %}



{% include 'components/flashed_messages.html' %}


{% include 'components/navbar.html' %}


{% include 'components/menu.html' %}


{% block content %}
  

  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="flex flex-col max-w-7xl mt-4 mx-auto">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead>
              <tr>
                
                <th scope="col" class="px-6 py-2 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Todo
                </th>
                <th scope="col" class="px-6 py-2 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-32">
                  Priority
                </th>
                <th scope="col" class="px-6 py-2 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-32">
                  Tags
                </th>
              
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              {% for todo in context.todos %}
              <tr class="hover:bg-fuchsia-50 hover:cursor-pointer">
                {% if context.edit == True and todo.id == edit_todo.id and not todo.done %}
                
                  <td class="px-6 py-2 whitespace-nowrap text-sm text-gray-400 flex flex-row items-center">
                
                    <svg class="w-auto mx-1.5 h-5
                      {{ 'text-white bg-fuchsia-700 rounded-full'
                      if todo.done else
                      'text-fuchsia-300 hover:text-fuchsia-600 h-5' }}" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  
                    <div class="w-full">
                      <form class="w-full mb-0" action="{{ url_for('todo.update', id=todo.id) }}" method="POST">
                        {{ edit_form.csrf_token }}
                        {{ edit_form.body(class="focus:ring-fuchsia-500 focus:border-fuchsia-500 block w-full sm:text-sm border-transparent rounded-md placeholder-fuchsia-300", autofocus=True, onfocus="var temp_value=this.value; this.value=''; this.value=temp_value" ) }}
                      </form>
                    </div>
                  </td>
                {% else %}
                  <td class="px-6 py-2 whitespace-nowrap text-sm text-gray-500 flex flex-row" ondblclick="window.location='{{ url_for('todo.update', id=todo.id) }}'">
                    <a href="{{ url_for('todo.check_off', id=todo.id) }}">
                      <svg class="w-auto mx-1.5 h-5
                        {{ 'text-white bg-fuchsia-700 rounded-full'
                        if todo.done else
                        'text-fuchsia-300 hover:text-fuchsia-600 h-5' }}" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </a>
                    <p>{{ todo.body }}</p>
                  </td>
                {% endif %}
                  <td class="px-6 py-2 whitespace-nowrap">
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-fuchsia-100 text-fuchsia-800">
                      Hoog
                    </span>
                  </td>
                  <td class="px-6 py-2 whitespace-nowrap">
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-fuchsia-100 text-fuchsia-800">
                      Test
                    </span>
                  </td>
                  
                </tr>
                
              {% endfor %}
              <tr class="hover:bg-fuchsia-50 hover:cursor-pointer">
                
                <td class="px-6 py-2 whitespace-nowrap text-sm text-gray-500 flex flex-row items-center">
                  <svg class="text-fuchsia-300 hover:text-fuchsia-600 h-5 w-auto mx-1.5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <div class="w-full">
                    <form class="w-full mb-0" action="{{ url_for('todo.create') }}" method="POST">
                      {{ form.csrf_token }}
                      {{ form.body(class="focus:ring-fuchsia-500 focus:border-fuchsia-500 block w-full sm:text-sm border-transparent rounded-md placeholder-fuchsia-300 leading-10", placeholder="...") }}
                    </form>
                  </div>
                </td>
                <td class="px-6 py-2 whitespace-nowrap">
                  <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-fuchsia-100 text-fuchsia-800">
                    
                  </span>
                </td>
                <td class="px-6 py-2 whitespace-nowrap">
                  <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-fuchsia-100 text-fuchsia-800">
                    
                  </span>
                </td>
                
              </tr>

              <!-- More rows... -->
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>




{% endblock content %}

app/templates/todo/projects.html
{% extends 'base.html' %}


{% block title %}
  Projects
{% endblock title %}



{% block errors %}
  {% include 'components/flashed_messages.html' %}
{% endblock errors %}



{% block navbar %}
  {% include 'components/navbar.html' %}
{% endblock navbar %}




{% block content %}

  projects
{% endblock content %}

app/templates/todo/team.html
{% extends 'base.html' %}


{% block title %}
  Team
{% endblock title %}



{% block errors %}
  {% include 'components/flashed_messages.html' %}
{% endblock errors %}



{% block navbar %}
  {% include 'components/navbar.html' %}
{% endblock navbar %}




{% block content %}
team
  
{% endblock content %}